# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: News
    url: post
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Research lines
    url: research_lines
    weight: 33
  - name: Projects
    url: project
    weight: 35
  - name: Publications
    url: publication
    weight: 40
  - name: Events (old)
    url: event
    weight: 50
  - name: Events
    url: conference
    weight: 55
  - name: Contact
    url: contact
    weight: 60
